#dev
server:
  port: 9000

---
#pid file save path
spring:
  application:
    name: springboot01
  pid:
    file: /data1/scraping/springboot01.pid
  zipkin:
    base-url: http://127.0.0.1:9411
---
logging:
  config: classpath:logback-local.xml


