server:
  port: 9010

---
#pid file save path
spring:
  application:
    name: simpleSpringboot
  pid:
    file: /data1/scraping/simpleSpringboot.pid
---
logging:
  config: classpath:logback-local.xml


